# <span style="color:RoyalBlue">Introducción a librerías básicas para uso científico</span>

<img src="images/python_ecosystem.png">

Las más usadas para cálculo científico y análisis de datos son:
- NumPy
- SciPy
- Pandas

## <span style="color:CornflowerBlue">**NumPy**</span>
[NumPy](https://numpy.org/) (**Num**-ber **Py**-thon) es la biblioteca estándar de Python para trabajar con vectores y matrices.
Extiende la funcionalidad de Python permitiendo el uso de expresiones vectorizadas (como las que emplea **Matlab**).

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" width = 450>

La principal ventaja de emplear Numpy en vez de las estructuras de datos nativas de Python es su eficiencia (rapidez), dado que ofrece nuevos tipos de variables que permiten generar expresiones vectorizadas, para las cuales hay funciones *precompiladas*, y escritas en *C*, lo que las hace muy rápidas.

Se puede pensar a estos arreglos de Numpy como listas de Python estándar en la que todos sus elementos tienen el mismo tipo. En el caso de las listas estándar de Python, los elementos eran estructuras abstractas que podían contener objetos de cualquier tipo, por lo tanto su manejo tiene un sobrecosto de almacenar los metadatos de tipos de cada elemento. En el caso de Numpy, como es requisito que todos los elementos sean del mismo tipo ese costo se omite y se pueden hacer funciones que operen más rápido sobre los datos. 

## Inicio

El primer requisito para usar esta biblioteca es importarla previo a su empleo

In [5]:
import numpy as np

## Tipos de datos

Los objetos básicos de esta biblioteca son los arreglos, que se pueden crear de la siguiente manera: 

In [6]:
a = np.array([1,2,3,4,5])   # Definición de un array a partir de una lista Python
b = np.array((6,7,8,9,10))  # Definición de un array a partir de una tupla Python
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


De igual manera se puede hacer para crear arreglos de múltiples dimensiones, conocer sus dimensiones o acceder a elementos específicos:

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 

In [13]:
print("Tamaño de a: {}".format(a.size))

Tamaño de a: 6


In [14]:
print("Dimensión de a: ", a.ndim)

Dimensión de a:  2


In [15]:
print("Contenido de a:\n", a)

Contenido de a:
 [[1 2 3]
 [4 5 6]]


In [18]:
print("Acceder a un elemento [1, 2] de a: {}".format(a[1, 2]))

Acceder a un elemento [1, 2] de a: 6


## Tipos especiales de arreglos

Existen tipos particulares de arreglos que serán de mucha utilidad para operaciones algebraica.
Entre ellos, vectores nulos, de unos o la matriz identidad:

In [21]:
a = np.zeros([1,30])
print("Vector nulo de 30 elementos, a:", a, "\n")

Vector nulo de 30 elementos, a: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]] 



In [22]:
b = np.ones([4,3])
print("Matriz de 4 filas y 3 columnas con todos sus valores iguales a uno b: \n", b, "\n")

Matriz de 4 filas y 3 columnas con todos sus valores iguales a uno b: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



In [23]:
c = np.eye(2) 
print ("Matriz identidad de 2x2\n", c, "\n")

Matriz identidad de 2x2
 [[1. 0.]
 [0. 1.]] 



Vectores de enteros consecutivos que se pueden usar como índices:

In [28]:
a = np.arange(0, 30, 3) # no incluye el 30
print("Vector con los enteros del 0 al 30 enumerados espaciados con un valor de 3 entre ellos:\n", a, "\n")

Vector con los enteros del 0 al 30 enumerados espaciados con un valor de 3 entre ellos:
 [ 0  3  6  9 12 15 18 21 24 27] 



In [29]:
b = np.linspace(0, 10, 100)  # incluye el 10
print("Vector con 100 elementos linealmente espaciados entre 0 y 10: \n", b, "\n")

Vector con 100 elementos linealmente espaciados entre 0 y 10: 
 [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768

Permutaciones aleatorios de enteros

In [31]:
a = np.arange(10)
a_perm = np.random.permutation(a)
print(a)
print(a_perm)

[0 1 2 3 4 5 6 7 8 9]
[9 8 1 2 6 5 0 7 4 3]


Vector con 1000 elementos de valores aleatorios entre 0 y 1:

In [8]:
a = np.random.rand(150) # La distribución de este vector es uniforme. Se puede usar *np.random.randn* para distribución normal
print(a)

[0.11990648 0.1466002  0.41881182 0.33591723 0.61012552 0.66689372
 0.21543401 0.69577257 0.57286595 0.64931999 0.10544679 0.30004141
 0.20686484 0.14858552 0.27969226 0.2801504  0.31172752 0.87458272
 0.46626325 0.39579983 0.347351   0.33023079 0.63102224 0.62226601
 0.43946118 0.02728847 0.30655019 0.38741728 0.40837193 0.8768767
 0.95402966 0.29335888 0.47396016 0.51328221 0.77266466 0.85610727
 0.84473138 0.85574149 0.92517042 0.96278251 0.55013241 0.69630152
 0.80618822 0.31902156 0.57056527 0.31070622 0.81577283 0.6358499
 0.98677958 0.17851124 0.4738832  0.47334979 0.08712882 0.97573199
 0.51919855 0.42689912 0.35949046 0.37016925 0.78574045 0.38759456
 0.41391608 0.07195028 0.97700599 0.18331277 0.6909122  0.21797781
 0.87486716 0.6153945  0.91418747 0.73426492 0.6364053  0.59505723
 0.66670867 0.23267549 0.38625476 0.45970418 0.84444096 0.63871052
 0.48292741 0.37281874 0.0593939  0.30935947 0.10370857 0.10286107
 0.96885954 0.89619639 0.21275355 0.7773755  0.13300888 0.731713

Mas info sobre [**random generators**](https://towardsdatascience.com/most-important-random-number-python-modules-to-keep-always-by-your-side-ef99a4ae624b)

### Modificación de la forma de arreglos
En muchos casos es conveniente por razones de eficiencia aplicar operaciones sobre vectores en lugar que hacerlo sobre matrices. En esos casos Numpy permite cambiar las dimensiones de los arreglos con la función *reshape*.
Esta función devuelve una vista del arreglo original, no una copia de su contenido.

Por ejemplo se puede cambiar la estructura de un arreglo 1D de 100 elementos a uno 2D de 20 x 5: 

In [33]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [34]:
b = a.reshape(20,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


Y se puede volver a convertir en una matriz, aunque se desconozca sus dimensiones a un vector 1D, operación que se llama aplanado o *flattening* haciendo: 

In [35]:
c = b.reshape(-1) 
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## Indexado y recortes

El indexado y recorte de subconjuntos de arreglos en Numpy es similar al estándar de Python. Una de las principales diferencias es que al asignar un segmento de un array en Numpy a otra variable, en realidad se opera sobre una vista en memoria de esos elementos, no se copian esos valores como se hace en listas ordinarias de Python:

In [4]:
a = np.arange(100)  # array del 0 al 99
b = a[3:10]
print(b)

[3 4 5 6 7 8 9]


In [7]:
b[0] = -99
print(b)

[-99   4   5   6   7   8   9]


In [9]:
print(a)  # ver 4to elemento

[  0   1   2 -99   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99]


Para forzar una copia se puede hacer:

In [11]:
a = np.arange(100)
b = a[3:10].copy()
print(b)
b[0] = -99
print(b)
print(a)  # no se modificó 4to elemento

[3 4 5 6 7 8 9]
[-99   4   5   6   7   8   9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### Indexado
A continuación se muestran algunas operaciones de indexado básicas:

In [12]:
a[1:5]     # índices de 1 a 4

array([1, 2, 3, 4])

In [13]:
a[:5]      # índices de 0 a 4

array([0, 1, 2, 3, 4])

In [14]:
a[2:]      # índices del 2 hasta el último elemento

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
a[::-1]    # reversión del arreglo

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [16]:
a[::2]     # índices desde el inicio al final salteando de a dos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Selección de filas o columnas completas:

In [37]:
# Creamos una matriz (5x4) con números aleatorios
A = np.round(10*np.random.rand(5,4), 1)
A 

array([[9. , 6.9, 3.6, 3.5],
       [5.5, 0.6, 1.2, 0.1],
       [5.2, 3.1, 0. , 8.8],
       [3.5, 3.9, 5.2, 7.8],
       [4.1, 3.3, 8.1, 6.6]])

Selección de la segunda fila completa

In [38]:
A[1,:]

array([5.5, 0.6, 1.2, 0.1])

Selección de la tercera columna completa:

In [39]:
A[:,2]    # Selección de la segunda fila completa

array([3.6, 1.2, 0. , 5.2, 8.1])

Selección de las filas 2 y 3 y de esas las columnas 3 y 4

In [40]:
A[1:3,2:4]

array([[1.2, 0.1],
       [0. , 8.8]])

También es posible indexar usando máscaras de índices. Esta alternativa es muy usada cuando se quiere elegir elementos que satisfagan cierta condición. El slicing por máscaras devuelve **es una copia y no una vista de memoria**.

In [41]:
a = np.arange(100, 200)
print(a)
b = a[[3,5,6]]
print(b)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
[103 105 106]


In [42]:
b[0] = -99
print(a)  # no se modificó el elemento

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


Este mismo tipo de indexado se puede emplear con condiciones lógicas de la sigueinte manera:

In [43]:
b = a[a<150]
b

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [44]:
b = a[(a<150) & (a>125)]
b

array([126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

### Ordenamiento de datos
Es posible usar la función de Numpy *sort* para ordenar los datos de una matriz por columnas:

In [45]:
print("Antes de ordenar")
print(A)
A.sort(axis=0)
print("Luego de ordenar")
print(A)

Antes de ordenar
[[9.  6.9 3.6 3.5]
 [5.5 0.6 1.2 0.1]
 [5.2 3.1 0.  8.8]
 [3.5 3.9 5.2 7.8]
 [4.1 3.3 8.1 6.6]]
Luego de ordenar
[[3.5 0.6 0.  0.1]
 [4.1 3.1 1.2 3.5]
 [5.2 3.3 3.6 6.6]
 [5.5 3.9 5.2 7.8]
 [9.  6.9 8.1 8.8]]


O por filas:

In [46]:
A.sort(axis=1)
A

array([[0. , 0.1, 0.6, 3.5],
       [1.2, 3.1, 3.5, 4.1],
       [3.3, 3.6, 5.2, 6.6],
       [3.9, 5.2, 5.5, 7.8],
       [6.9, 8.1, 8.8, 9. ]])

### Transmisión de matrices (Broadcasting)
La transmisión de matrices es un mecanismo que permite a Numpy operar aritméticamente sobre arreglos de diferentes tamaños. Una situación común es cuando se quiere realizar una operación que aplica un vector más pequeño múltiples veces sobre otro otro vector más grande.

Por ejemplo, sumar un vector constante a cada fila de una matriz. Podríamos hacerlo así:

In [47]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([1, 0, 1])
print(b)
y = np.empty_like(a)   # Crea una matriz vacía del tamaño de a

# Sumar el vector b a cada fila de a:
for i in range(4):
    y[i, :] = a[i, :] + b

print (y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Si bien ese procedimiento funciona, cuando la matriz *a* es muy grande, calcular un bucle explícito en Python sería muy lento. Otra opción sería hacer múltiples copias para llevar a b al tamaño de a:

In [48]:
bb = np.tile(b, (4, 1))  # Apila 4 copias of b una arriba de la otra
print (bb)

y = a + bb
print (y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


El mecanismo de *broadcasting* o transmisión de Numpy permite hacer algo parecido a lo anterior pero sin la necesidad de crear esa versión con múltiples copias de b:

In [49]:
y = a + b
print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Velocidad de procesamiento
A continuación veremos una comparación de velocidades de ejecución de una operación de suma de 1 millón de elementos usando la función de suma estándar de Python, y su contraparte de Numpy: 

In [51]:
b = np.random.rand(1000000)
%timeit sum(b)     # sum de librría estándar
%timeit np.sum(b)  # sum de NumPy

104 ms ± 2.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
643 µs ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Ejercitación 1

<img src="images/problem_1.png" alt= “” width="800">

**Calcular la probabilidad de que salga un 6**

Posible solución tradicional

In [80]:
def probabilidad_con_for(N):
    import random

    M = 0  # cantidad de veces que salió un 6

    for i in range(N):
        valor = random.randint(1, 6)  # lanzamos el dado
        if valor == 6:  # verificamos si es 6
            M += 1  # contamos un 6

    return M/N

In [92]:
N = 10000  # cantidad de lanzamientos

p_1 = probabilidad_con_for(N)
print(p_1)

0.1683


## Ejercitación 2

Estimar el valor de Pi utilizando la técnica de Monte Carlo

<img src="images/pi-monte-carlo-square-circle.png" width=300>
Para resolverlo, pensemos en un proceso de generar puntos completamente aleatorio y todas las posiciones de dichos puntos son igualmente probables. 

En este caso, podemos decir que el número de puntos que caen dentro del círculo ($N_c$) dividido por el número total puntos totales (que caen en el cuadrado) ($N_t$) cumple con lo siguiente:

$$
  \frac{N_c}{N_t}=\frac{\mathrm{Area\:circulo}}{\mathrm{Area\:cuadrado}}=\frac{\pi r^{2}}{(2r)^{2}}=\frac{\pi}{4}
$$
$$
    \pi = 4 \times \frac{N_c}{N_t}
$$

Para saber si un punto cayó dentro del círculo, las coordenadas deberían cumplir la siguiente ecuación:
$$ x^{2} + y^{2} \leq 1 $$

In [98]:
import random
import math

N_t = 1000000  # puntos totales
N_c = 0  # contador de puntos en el círculo

for i in range(0, N_t):
    x = random.uniform(-1.0, 1.0)
    y = random.uniform(-1.0, 1.0)
    
    if math.sqrt(x*x + y*y) <= 1:  # verifica si cae dentro del círculo
        N_c += 1

pi = 4 * N_c/N_t  # cálculo de Pi

print("Estimación de Pi: %.7f" % pi)
print("Valor de Pi:      %.7f" % math.pi)

Estimación de Pi: 3.1425520
Valor de Pi:      3.1415927


## Otras funciones útiles de NumPy

Operaciones sobre los elementos del vector

In [7]:
a = np.arange(5) 
b = np.arange(5) 
print(a)
print(b)

[0 1 2 3 4]
[0 1 2 3 4]


In [2]:
a + b

array([0, 2, 4, 6, 8])

In [3]:
a - b


array([0, 0, 0, 0, 0])

In [4]:
a**2

array([ 0,  1,  4,  9, 16])

In [5]:
10 * np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [8]:
a * b  # multiplicación elemento a elemento

array([ 0,  1,  4,  9, 16])

Operaciones matriciales y vectoriales

In [23]:
M1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
M2 = np.array([[9,8,7,6],[5,4,3,3],[2,1,2,0]])

print("Matriz 1 {}".format(M1.shape))
print(M1)
print("Matriz 2 {}".format(M2.shape))
print(M2)

Matriz 1 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz 2 (3, 4)
[[9 8 7 6]
 [5 4 3 3]
 [2 1 2 0]]


In [13]:
np.matmul(M1, M2)  # multiplicación matricial

array([[ 25,  19,  19,  12],
       [ 73,  58,  55,  39],
       [121,  97,  91,  66]])

In [29]:
M1 @ M2  # otra opción más corta

array([[ 25,  19,  19,  12],
       [ 73,  58,  55,  39],
       [121,  97,  91,  66]])

In [28]:
# Intentar hacer M2 x M1

In [15]:
a1 = np.array([1,2,3])
a2 = np.array([2,1,2])

In [18]:
np.dot(a1, a2)  # producto punto o escalar

10

In [19]:
np.cross(a1, a2)  # producto cruz o vectorial

array([ 1,  4, -3])

Una de las razones más comunes de uso del paquete NumPy es su módulo de álgebra lineal [numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [34]:
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
print(a)

[[1. 2.]
 [3. 4.]]


In [35]:
a_inv = np.linalg.inv(a) # matriz inversa
print(a_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Para resolver el sistema de ecuaciones
$$ 3 x_0 + x_1 = 9 $$
$$ x_0 + 2 x_1 = 8 $$

In [37]:
# Se representa con matrices de la forma Ax = b
A = np.array([[3,1], [1,2]])
b = np.array([9,8])
# Para resolver se debe realizar x = A⁻¹b, que NumPy lo realiza con la función "solve"
x = np.linalg.solve(A, b)
x

array([2., 3.])

## Ejercitación 3

A partir de la base de datos del Personal de Ciencia y Tecnología de Argentina (extraído del SICYTAR) del año 2018, determinar:
- la cantidad de personas que trabajan en CyT, 
- el promedio de edad, 
- el promedio y desviación estándar de la producción por persona en los último 4 años, y 
- el número máximo de producciones en los últimos 4 años de una persona.

*Ayuda*: utilizar la función `numpy.loadtext` para cargar el archivo con los datos. Columnas con índice 3 y 12.